site_name: Language documentation script collection
repo_url: https://github.com/fmatter/langdoc-script-collection
plugins:
  - search
  - tags:
      tags_file: tags.md
  # - mkdocstrings
  - include-markdown
  - git-authors
  - git-revision-date-localized
extra_css:
  - style.css
extra:
  tags:
    flex: SIL's [FieldWorks](https://software.sil.org/fieldworks/)
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - toc.integrate
    - content.code.copy
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      # pygments_style: railscast
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
